version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - node
  node:
    image: danilocavalcantefranca/node-inflate-jwt:tagname
    ports:
      - "3000:3000"