version: '3'
services:
  app:
    build:
      context: .
      #dockerfile: Dockerfile
    depends_on:
      - node
  node:
    image: danilocavalcantefranca/test-github-actions
    ports:
      - "3001:3000"