version: '3'
services:
  my-service:
    network_mode: host
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - node
  node:
    image: danilocavalcantefranca/test-github-actions
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"] 
      timeout: 10s
      retries: 5