version: '3'

services:
  cypress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - front
  front:
    build:
      context: ./front/example-front-github-actions
    ports:
      - "3000:3000"