name: Automated Tests

on: push
jobs: 
  test:
    name: Cypress run
    runs-on: ubuntu-latest
    container: danilocavalcantefranca/test-github-actions
    steps:
      - name: Docker build
        run: |-
          docker build -t test-github-actions .
      - name: Docker run
        run: |-
          docker run test-github-actions -p 3000:3000
      - uses: actions/checkout@v2
      - name: Cypress run 
        uses: cypress-io/github-action@v2
        with: 
          record: false  
          #parallel: true
          #spec: cypress/integration/gui/${{ matrix.containers }}.js
          command: npx cypress run --config baseUrl=http://localhost:3000/ --config video=false
          #command: npm start
