name: Automated Tests

on: push
jobs: 
    runs-on: ubuntu-latest
    container: danilocavalcantefranca/test-github-actions
      command: npm start
  test:
    name: Cypress run
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run 
        uses: cypress-io/github-action@v2
        with: 
          record: false  
          #parallel: true
          #spec: cypress/integration/gui/${{ matrix.containers }}.js
          command: npx cypress run --config baseUrl=http://localhost:3000/ --config video=false
          #command: npm start
