name: Automated Tests


on: push
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test docker
      run: docker-compose up --build --abort-on-container-exit
    - name: test docker stop
      run: docker-compose stop